name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: [cicd-o11y]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@v1
        env:
          OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
        with:
          otlpEndpoint: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
          otlpHeaders: "Authorization=Basic ${{ secrets.OTLP_HEADERS }}"
          otelServiceName: cicd-observability-github-actions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
