name: OpenTelemetry Export Trace

on:
  workflow_run:
    workflows: [cicd-o11y]
    types: [completed]

jobs:
  otel-export-trace:
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        id: export
        uses: corentinmusard/otel-cicd-action@v1
        env:
          # OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
        with:
          otlpEndpoint: "grpc://api.honeycomb.io:443"
          otlpHeaders: "${{ secrets.OTLP_HEADERS }},x-honeycomb-dataset=cicd"
          otelServiceName: cicd-observability-github-actions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
      - run: echo ${{ steps.export.outputs.traceId }}
